# Generated by Django 4.2 on 2025-01-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admin_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='membership_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_leader_access',
            field=models.BooleanField(default=False),
        ),
    ]
