# Generated by Django 4.2 on 2025-01-25 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employee_admin_access_employee_department_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='department.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
