# Generated by Django 4.2 on 2025-01-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_user_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_access',
            new_name='co_worker_access',
        ),
    ]
